<a href="https://en.wikipedia.org/wiki/Global_warming#History">Wikipedia</a>
<a href="https://www.nrdc.org/stories/how-you-can-stop-global-warming">How to Help</a>

<div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" 			    title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" 			    title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>