<nav class="navigation">
    <ul>
        <li>
            <a href="login.php">Log In</a>
        </li>

        <li>
        	<a href="index.php">Home</a>
        </li>

        <!--<li> TEMPORARY - cannot see the "sign up" nav
        	<a href="causes.php">Causes</a>
    	</li>
        -->

    	<li>
           	<a href="actions.php">Actions</a>
        </li>

        <li>
            <a href="future.php">The Future of Planet Earth</a>
        </li>

        <li>
            <a href="form.php" id="last">Sign Up to Volunteer</a>
        </li>
    </ul>
</nav>