<nav class="navigation">
    <ul>
        <li>
        	<a href="index.php">Home</a>
        </li>

        <li>
        	<a href="causes.php">Causes</a>
    	</li>

    	<li>
           	<a href="actions.php">Actions</a>
        </li>

        <li>
            <a href="future.php">The Future of Planet Earth</a>
        </li>

        <li>
            <a href="future.php">The Future</a>
        </li>
        
        <li>
         <a href="admin.php" id="last">Login</a>
        </li>

    </ul>
</nav>